op_result = RunExecutionResult(
    results=[
        RunResult(
            status={RunStatus.Success: 'success'}, 
            timing=[
                TimingInfo(
                    name='compile', 
                    started_at=datetime.datetime(2022, 6, 19, 6, 23, 18, 213498), 
                    completed_at=datetime.datetime(2022, 6, 19, 6, 23, 18, 220153)
                ), 
                TimingInfo(
                    name='execute', 
                    started_at=datetime.datetime(2022, 6, 19, 6, 23, 18, 220657), 
                    completed_at=datetime.datetime(2022, 6, 19, 6, 23, 18, 220692)
                )
            ], 
            thread_id='Thread-5', 
            execution_time=0.008560895919799805, 
            adapter_response={}, 
            message=None, 
            failures=None, 
            node=CompiledModelNode(
                raw_sql="-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/index.ipynb (unless otherwise specified).\nselect *\nfrom {{ ref('my_second_dbt_model') }}", 
                compiled=True, 
                database='sample-dbt-learn-project', 
                schema='jaffle_shop', fqn=['my_dbt_project', 'my_third_model'], 
                unique_id='model.my_dbt_project.my_third_model', 
                package_name='my_dbt_project', 
                root_path='/home/butch2/play/experiments/nbdbt/my_dbt_project', 
                path='my_third_model.sql', 
                original_file_path='models/my_third_model.sql', 
                name='my_third_model', 
                resource_type={NodeType.Model: 'model'}, 
                alias='my_third_model', 
                checksum=FileHash(
                    name='sha256', 
                    checksum='0cabe64c25a02199ef8517ceb1a3a12bbcda9761bce6a6ee26f47255cdbdd4d0'
                    ), 
                config=NodeConfig(
                    _extra={}, 
                    enabled=True, 
                    alias=None, 
                    schema=None, 
                    database=None, 
                    tags=[], 
                    meta={}, 
                    materialized='view', 
                    persist_docs={}, 
                    post_hook=[], 
                    pre_hook=[], 
                    quoting={}, 
                    column_types={}, 
                    full_refresh=None, 
                    unique_key=None, 
                    on_schema_change='ignore'
                ), 
                _event_status={
                    'node_status': {RunningStatus.Executing: 'executing'}
                }, 
                tags=[], 
                refs=[
                    ['my_second_dbt_model']
                ], 
                sources=[], 
                depends_on=DependsOn(
                    macros=[], 
                    nodes=['model.my_dbt_project.my_second_dbt_model']
                ), 
                description='', 
                columns={}, 
                meta={}, 
                docs=Docs(show=True), 
                patch_path=None, 
                compiled_path='target/compiled/my_dbt_project/models/my_third_model.sql', 
                build_path=None, 
                deferred=False, 
                unrendered_config={}, 
                created_at=1655619796.9613981, 
                config_call_dict={}, 
                compiled_sql='-- AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/index.ipynb (unless otherwise specified).\nselect *\nfrom `sample-dbt-learn-project`.`jaffle_shop`.`my_second_dbt_model`', 
                extra_ctes_injected=True, 
                extra_ctes=[], 
                relation_name='`sample-dbt-learn-project`.`jaffle_shop`.`my_third_model`', 
                _pre_injected_sql=None
            ), 
            agate_table=None
        )
    ], 
    elapsed_time=1.2674076557159424, 
    args={
        'write_json': True, 
        'printer_width': 80, 
        'profiles_dir': '/home/butch2/.dbt', 
        'event_buffer_size': 100000, 
        'project_dir': '/home/butch2/play/experiments/nbdbt/my_dbt_project', 
        'parse_only': False, 
        'select': ['models/my_third_model.sql'], 
        'which': 'compile', 
        'rpc_method': 'compile', 
        'indirect_selection': 'eager'
    }, 
    generated_at=datetime.datetime(2022, 6, 19, 6, 23, 18, 313902)
)