# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IN_NBDBT_TEST": "00_dbt_cellmagic.ipynb",
         "dbt.tracking.active_user": "00_dbt_cellmagic.ipynb",
         "dbt.flags.INDIRECT_SELECTION": "00_dbt_cellmagic.ipynb",
         "dbt.flags.WRITE_JSON": "00_dbt_cellmagic.ipynb",
         "dbt.flags.QUIET": "00_dbt_cellmagic.ipynb",
         "DbtMagicObject": "00_dbt_cellmagic.ipynb",
         "DbtMagicObject.ref": "00_dbt_cellmagic.ipynb",
         "write_dbt": "00_dbt_cellmagic.ipynb"}

modules = ["dbt_cellmagic.py"]

doc_url = "https://butchland.github.io/nbdbt/"

git_url = "https://github.com/butchland/nbdbt/tree/master/"

def custom_doc_links(name): return None
